services:
  monthly-report-scheduler:
    build: .
    restart: unless-stopped
    environment:
      API_BASE_URL: http://api-report:8080
      MONTHLY_REPORT_JOB_SECRET: ${MONTHLY_REPORT_JOB_SECRET}
      SCHEDULE_TIME_ZONE: America/Sao_Paulo
      SCHEDULE_HOUR: 0
      SCHEDULE_MINUTE: 5
      PORT: 8090
    ports:
      - "8090:8090"
